### ISSUE TITLE
Feature Request: Include `privatemode-proxy` inside this tool

### ISSUE THREAD

**Issue by dhcgn** [dhcgn/paperless-ngx-privatemode-ai#4]
## Summary

Add a new configuration option `privatemode-ai-api-key` that allows users to choose between using a remote privatemode.ai service (like Docker deployment) or running the privatemode.ai proxy locally within this application.

## Problem Statement

Currently, users must configure a remote `base_url` for the LLM service in the configuration:

```yaml
llm:
  api:
    base_url: "http://192.168.3.10:9876"  # Remote privatemode.ai instance
    endpoint: "/v1/chat/completions"
```

This requires users to:
- Set up and maintain a separate privatemode.ai Docker container or service
- Configure network access between the paperless-ngx-privatemode-ai application and the remote service
- Manage additional infrastructure complexity

## Proposed Solution

Add a new optional configuration field `privatemode-ai-api-key` under the `llm` section:

```yaml
llm:
  api:
    base_url: "http://192.168.3.10:9876"  # Used when privatemode-ai-api-key is not set
    endpoint: "/v1/chat/completions"
    privatemode-ai-api-key: "your-api-key-here"  # NEW: Optional field
  models:
    title_generation: "ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4"
    content_extraction: "google/gemma-3-27b-it"
```

### Configuration Logic

When `privatemode-ai-api-key` is set:
- **Override `base_url`** to `http://localhost:PORT` (where PORT is dynamically assigned)
- **Start local privatemode.ai proxy** within the application
- **Route LLM requests** through the local proxy instead of the remote service

When `privatemode-ai-api-key` is NOT set:
- **Use existing behavior** - connect to remote `base_url`
- **No changes** to current functionality

### Implementation Details

1. **Configuration Validation**
   ```go
   type LLMConfig struct {
       API struct {
           BaseURL              string `yaml:"base_url"`
           Endpoint             string `yaml:"endpoint"`
           PrivateModeAIAPIKey  string `yaml:"privatemode-ai-api-key,omitempty"`
       } `yaml:"api"`
       // ...existing fields
   }
   ```

2. **Runtime Logic**
   ```go
   func (c *Config) GetLLMBaseURL() string {
       if c.LLM.API.PrivateModeAIAPIKey != "" {
           // Start local proxy and return localhost URL
           return c.startLocalPrivateModeAIProxy()
       }
       return c.LLM.API.BaseURL  // Use configured remote URL
   }
   ```

3. **Local Proxy Management**
   - Start privatemode.ai proxy as a goroutine when application starts
   - Use available port detection (e.g., `net.Listen(":0")`)
   - Handle proxy lifecycle (start/stop with application)
   - Add proper error handling and logging

### For Users
- **Simplified Deployment**: No need to manage separate Docker containers
- **Reduced Infrastructure**: Single application handles everything
- **Easier Configuration**: Just add API key instead of setting up remote service
- **Better Security**: No network exposure of LLM proxy

### For Developers
- **Backward Compatibility**: Existing configurations continue to work unchanged
- **Flexibility**: Support both deployment models
- **Reduced Support Burden**: Fewer infrastructure-related issues

### Example 1: Using Local Proxy (New Feature)
```yaml
llm:
  api:
    # base_url is ignored when privatemode-ai-api-key is set
    base_url: "http://ignored-when-api-key-set:9876"
    endpoint: "/v1/chat/completions"
    privatemode-ai-api-key: "pm-1234567890abcdef"  # Enables local proxy
  models:
    title_generation: "ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4"
    content_extraction: "google/gemma-3-27b-it"
```

### Example 2: Using Remote Service (Existing Behavior)
```yaml
llm:
  api:
    base_url: "http://192.168.3.10:9876"  # Remote privatemode.ai instance
    endpoint: "/v1/chat/completions"
    # privatemode-ai-api-key not set - uses remote service
  models:
    title_generation: "ibnzterrell/Meta-Llama-3.3-70B-Instruct-AWQ-INT4"
    content_extraction: "google/gemma-3-27b-it"
```

## Files to Modify

1. **`config.go`** - Add new configuration field and validation
2. **`llm.go`** - Modify client initialization to handle local vs remote
3. **`main.go`** - Add proxy lifecycle management
4. **`config.sample.yaml`** - Add commented example of new field
5. **`config.test.yaml`** - Add test configuration examples
6. **`README.md`** - Update documentation with new deployment option

### Phase 1: Configuration Structure
- [ ] Add `privatemode-ai-api-key` field to config structs
- [ ] Update config validation and parsing
- [ ] Add unit tests for configuration

### Phase 2: Local Proxy Integration
- [ ] Implement local proxy startup/shutdown
- [ ] Add port management and detection
- [ ] Handle proxy authentication with API key

### Phase 3: Runtime Logic
- [ ] Modify LLM client to use appropriate base URL
- [ ] Add logging and error handling
- [ ] Implement graceful fallback mechanisms

### Phase 4: Documentation and Testing
- [ ] Update all configuration examples
- [ ] Add integration tests for both modes
- [ ] Update README with deployment options

### Current Workflow
1. Deploy privatemode.ai Docker container
2. Configure network access
3. Set `base_url` in config
4. Run paperless-ngx-privatemode-ai

### New Workflow (with API key)
1. Get privatemode.ai API key
2. Set `privatemode-ai-api-key` in config
3. Run paperless-ngx-privatemode-ai (proxy starts automatically)

## Backward Compatibility

✅ **Fully backward compatible** - existing configurations work unchanged
✅ **Optional feature** - users can choose their preferred deployment method
✅ **No breaking changes** - default behavior remains the same
